tugas API 1/mysite/myapp/urls.py
from django.urls import path
from myapp import views,views_api

app_name = 'myapp'
urlpatterns = [
    path('', views.home, name='home'),   
    path('read/', views.readStudent, name='read-data-student'),   
    path('create/', views.createStudent, name='create-data-student'),   
    path('update/<str:id>', views.updateStudent, name='update-data-student'),   
    path('delete/<str:id>', views.deleteStudent, name='delete-data-student'),   #urls untuk Course   
    path('read/course', views.readCourse, name='read-data-course'),   
    path('create/course', views.createCourse, name='create-data-course'),   
    path('update/course/<str:id>', views.updateCourse, name='update-data-course'),   
    path('delete/course/<str:id>', views.deleteCourse, name='delete-data-course'),   
    path('api/course/', views_api.apiCourse, name='api-view-data-course'),]

tugas API 1/mysite/myapp/templates/course.html
{% load static %} {% block content %} {% if messages %}
<div class="alert alert-success">
  {% for message in messages %} <strong>{{ message }}</strong> {% endfor %}
</div>
{% endif %}
<a href="{% url 'myapp:create-data-course'%}">Create</a>
<table border="1">
  <thead>
    <tr>
      <td>Course</td>
      <td>Created Date</td>
      <td>Actions</td>
    </tr>
  </thead>
  <tbody>
    {% for obj in data_list%}
    <tr>
      <td>{{obj.course_name}}</td>
      <td>{{obj.course_created_date}}</td>
      <td>
        <a href="{% url 'myapp:update-data-course' obj.course_id %}"
          >Update</a
        >
        <br />
        <a href="{% url 'myapp:delete-data-course' obj.course_id %}"
          >Delete</a
        >
      </td>
    </tr>
    {% empty%}
    <h1>Data masih kosong</h1>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

tugas API 1/mysite/myapp/templates/form.html
{% load static %} 
{% block content %}
<div class="container">
  <div class="row">
    <div class="main_business">
      <div class="col-md-12">
        {% if form.errors %}
        <div class="alert alert-danger"><strong>{{form.errors}}</strong></div>
        <br />
        {% endif %}
      </div>
    </div>
  </div>
</div>
<form method="post" id="create-form" name="create-form">
  {% csrf_token %}
  <div>
    <label>Input Nama Lengkap</label>
    <input type="text" name="fullname" id="fullname" />
  </div>
  <div>
    <label>Input NIM Lengkap</label> <input type="text" name="nim" id="nim" />
  </div>
  <div>
    <label>Input Email Lengkap</label>
    <input type="email" name="email" id="email" />
  </div>
  <div class="panel-footer text-center">
    <button class="btn btn-primary m-top-20">Simpan</button>
  </div>
</form>
{% endblock %}

tugas API 1/mysite/myapp/templates/index.html
{% load static %} {% block content %} {% if messages %}
<div class="alert alert-success">
  {% for message in messages %}
  <strong>{{ message }}</strong>
  {% endfor %}
</div>
{% endif %}
<a href="{% url 'myapp:create-data-student' %}">Create</a>
<table border="1">
  <thead>
    <tr>
      <td>NIM</td>
      <td>Nama</td>
      <td>e-mail</td>
      <td>Actions</td>
    </tr>
  </thead>
  <tbody>
    {% for obj in data_list%}
    <tr>
      <td>{{obj.account_user_student_number}}</td>
      <td>{{obj.account_user_fullname}}</td>
      <td>{{obj.account_user_related_user}}</td>
      <td>
        <a
          href="{% url 'myapp:update-data-student' obj.account_user_related_user %}"
          >Update</a
        >
        <br />
        <a
          href="{% url 'myapp:delete-data-student' obj.account_user_related_user %}"
          >Delete</a
        >
      </td>
    </tr>
    {% empty%}
    <h1>Data masih kosong</h1>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

tugas API 1/mysite/myapp/templates/update.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Update Student Data</title>
  </head>
  <body>
    <div class="container mt-5">
      <h2 class="mb-4">Update Student Data</h2>
      <form method="POST">
        {% csrf_token %} {% for field in form %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field }} {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
          {% endif %} {% for error in field.errors %}
          <div class="invalid-feedback">{{ error }}</div>
          {% endfor %}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
    </div>
  </body>
</html>